services:
  - type: web
    name: factory-dashboard-api
    runtime: python
    repo: https://github.com/Dutta-Raj/factory-monitoring-dashboard
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend